# Generated by Django 4.2 on 2025-12-25 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cis', '0025_student_profile_last_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1098T',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_year', models.IntegerField(help_text='Calendar year for the tax form (e.g., 2024)')),
                ('payments_received', models.DecimalField(decimal_places=2, help_text='Box 1: Payments received for qualified tuition', max_digits=10)),
                ('scholarships_grants', models.DecimalField(decimal_places=2, help_text='Box 5: Scholarships or grants', max_digits=10)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, help_text='Box 4: Adjustments made for a prior year', max_digits=10)),
                ('scholarship_adjustments', models.DecimalField(decimal_places=2, default=0, help_text='Box 6: Adjustments to scholarships for a prior year', max_digits=10)),
                ('student_name', models.CharField(max_length=255)),
                ('student_tin', models.CharField(blank=True, max_length=11)),
                ('student_address', models.TextField()),
                ('file_path', models.CharField(help_text='S3 path to the PDF file', max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this form is available for student download')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_1098t_forms', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_1098t_records', to='cis.student')),
            ],
            options={
                'verbose_name': '1098-T Form',
                'verbose_name_plural': '1098-T Forms',
                'db_table': 'form_1098t',
                'ordering': ['-tax_year', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Form1098TDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('file_path_snapshot', models.CharField(max_length=500)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='django_1098t.form1098t')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_1098t_downloads', to='cis.student')),
            ],
            options={
                'verbose_name': '1098-T Download',
                'verbose_name_plural': '1098-T Downloads',
                'db_table': 'form_1098t_download',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='form1098tdownload',
            index=models.Index(fields=['form', 'downloaded_at'], name='form_1098t__form_id_f543d1_idx'),
        ),
        migrations.AddIndex(
            model_name='form1098tdownload',
            index=models.Index(fields=['student', 'downloaded_at'], name='form_1098t__student_bc2cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='form1098t',
            index=models.Index(fields=['student', 'tax_year', 'is_published'], name='form_1098t_student_c2a6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='form1098t',
            index=models.Index(fields=['tax_year', 'is_published'], name='form_1098t_tax_yea_595cd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='form1098t',
            constraint=models.UniqueConstraint(condition=models.Q(('is_published', True)), fields=('student', 'tax_year'), name='unique_published_form_per_student_year'),
        ),
    ]
